### PR TITLE
fea: added more social media handles

### PR DESCRIPTION
**Pull request by a-sksingh113**
description:
new social media handles added.
also layout is responsive

fixes#19

desktop view:

Screenshot 2024-10-23 025213

and this phone view:
Screenshot 2024-10-23 025317

### CODE REVIEW

**Comment by Harsh-git98** [comment]
image

Thank you for the submission! Overall, the implementation looks good, but I noticed that the current layout is not fully responsive on mobile devices.

**Comment by a-sksingh113** [comment]
thank you for your feedback, I'll make responsive  layout .

**Comment by a-sksingh113** [comment]
Please give review my commit

**Comment by Harsh-git98** [comment]
### :white_check_mark: Pull Request Approved :white_check_mark:

#### PR Summary
- Added additional social media handles for expanded user connectivity.
- Verified links and icons for functionality and consistency across platforms.

#### Next Steps
- Merged into the `main` branch for deployment.

Thank you for enhancing our social reach!

**Pull request merged**
